POST http://localhost:8080/store
Content-Type: application/json

{
    "key": "exampleKey",
    "value": "exampleValue"
}

---

GET http://localhost:8080/retrieve/exampleKey

---

DELETE http://localhost:8080/delete/exampleKey